// !Only used in Section_4
export const Skill_data: Skill_data[] = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  // {
  //   skill_name: "Redux",
  //   Image: "/redux.png",
  //   width: 80,
  //   hight: 80,
  // },
  // {
  //   skill_name: "React Query",
  //   Image: "/reactquery.png",
  //   width: 80,
  //   hight: 80,
  // },
  {
    skill_name: "NextJS 13",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Solidity",
    Image: "/solidity.svg",
    width: 80,
    hight: 80,
  },
  // {
  //   skill_name: "Next Auth",
  //   Image: "https://next-auth.js.org/img/logo/logo-sm.png",
  //   width: 80,
  //   hight: 80,
  // },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  // {
  //   skill_name: "Stripe Payment",
  //   Image: "/stripe.webp",
  //   width: 80,
  //   hight: 80,
  // },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  // {
  //   skill_name: "Express js",
  //   Image: "/express.png",
  //   width: 80,
  //   hight: 80,
  // },
  // {
  //   skill_name: "Mongo db",
  //   Image: "/mongodb.png",
  //   width: 40,
  //   hight: 40,
  // },
  // {
  //   skill_name: "Firebase",
  //   Image: "/Firebase.png",
  //   width: 55,
  //   hight: 55,
  // },
  // {
  //   skill_name: "Postgres SQL",
  //   Image: "/postgres.png",
  //   width: 70,
  //   hight: 70,
  // },
  // {
  //   skill_name: "My SQL",
  //   Image: "/mysql.png",
  //   width: 70,
  //   hight: 70,
  // },
  // {
  //   skill_name: "Prisma",
  //   Image: "/prisma.webp",
  //   width: 70,
  //   hight: 70,
  // },
  // {
  //   skill_name: "Graphql",
  //   Image: "/graphql.png",
  //   width: 80,
  //   hight: 80,
  // },
  // {
  //   skill_name: "React Native",
  //   Image: "/ReactNative .png",
  //   width: 70,
  //   hight: 70,
  // },
  // {
  //   skill_name: "Docker",
  //   Image: "/docker.webp",
  //   width: 70,
  //   hight: 70,
  // },
  // {
  //   skill_name: "Figma",
  //   Image: "/figma.png",
  //   width: 50,
  //   hight: 50,
  // },
  // {
  //   skill_name: "Web Socket",
  //   Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
  //   width: 70,
  //   hight: 70,
  // },
  // {
  //   skill_name: "Go",
  //   Image: "/go.png",
  //   width: 60,
  //   hight: 60,
  // },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];

// TODO: Change image of projects
export const Project: Project_data[] = [
  {
    title: "Modern NextJS 13 Portfolio",
    projectKey: "mNjs13P",
    technology_feature: [
      "TypeScript",
      "React",
      "Redux",
      "NextJS 13",
      "Tailwind",
      "Framer Motion",
      "ThreeJS",
    ],
    about_this_app:
      "Welcome to my portfolio, where creativity thrives. Explore my captivating work with StarMode interactivity, a user-friendly Drop Down NavBar, and stunning custom star-colored animations powered by ThreeJS and Framer Motion. Experience a world of innovation and endless possibilities.",
    package: [
      "@heroicons/react",
      "@react-three/drei",
      "@react-three/fiber",
      "framer-motion",
      "maath",
      "react-redux",
      "@reduxjs/toolkit",
    ],
    future_improvements: "",
    live_link: "",
    gitHub_link: "https://github.com/r-tom90/starPortfolio",
    frontend_download_link:
      "https://github.com/r-tom90/starPortfolio/archive/refs/heads/main.zip",
    backend_download_link: "",
    project_image: "/project-profile.png",
    project_desc:
      "Explore my portfolio with StarMode, animations, and a user-friendly interface. Innovation awaits!",
    Type: "NextJS 13",
    indevelopment: false,
  },
  {
    title: "OT Health Coach",
    projectKey: "otHC",
    technology_feature: ["TypeScript", "React", "Tailwind"],
    about_this_app:
      "A stunning and refined landing page for a health coach, complete with a seamless contact form for effortless communication.",
    package: [
      "@formspree/react",
      "embla-carousel-react",
      "react-icons",
      "react-router-dom",
    ],
    future_improvements: "",
    live_link: "",
    gitHub_link: "https://github.com/r-tom90/OtHealthCoach",
    frontend_download_link:
      "https://github.com/r-tom90/OtHealthCoach/archive/refs/heads/main.zip",
    backend_download_link: "",
    project_image: "/project-otHealthCoach.png",
    project_desc: "Simple, but yet elegant landing page for a health coach.",
    Type: "React (Vite)",
    indevelopment: false,
  },
  {
    title: "MuskATears",
    projectKey: "muskATears",
    technology_feature: [
      "JavaScript",
      "React",
      "NextJS 13",
      "Tailwind",
      "Solidity",
    ],
    about_this_app:
      "MuskATears is an innovative community Meme Coin project that aims to foster growth and prosperity within the community. Embracing the mission of combating censorship, it seeks to empower individuals and promote freedom of expression.",
    package: ["recharts", "sweetalert2", "react-icons"],
    future_improvements: "",
    live_link: "https://www.muskatears.com/",
    gitHub_link: "https://github.com/r-tom90/muskatears",
    frontend_download_link:
      "https://github.com/r-tom90/muskatears/archive/refs/heads/main.zip",
    backend_download_link:
      "https://etherscan.io/token/0x9d04ceaae75ddbf2ba93c0abe670899120d20e1f#code",
    project_image: "/project-muskATears.png",
    project_desc:
      "A community Meme Coin project, empowering growth and fighting censorship.",
    Type: "NextJS 13",
    indevelopment: false,
  },
  {
    title: "MuskATears NFT Emporium",
    projectKey: "muskATearsNE",
    technology_feature: [
      "JavaScript",
      "React",
      "NextJS 13",
      "Framer Motion",
      "Tailwind",
      "Solidity",
    ],
    about_this_app:
      "Welcome to the MuskATears NFT Emporium, an innovative platform that empowers you to effortlessly mint, buy, and sell NFTs on the Ethereum blockchain. With the cutting-edge integration of the ThirdWebs SDK, experience a seamless and secure environment to explore and engage with the exciting world of digital art and collectibles.",
    package: [
      "@thirdweb-dev/chain",
      "@thirdweb-dev/react",
      "@thirdweb-dev/sdk",
      "embla-carousel-react",
      "framer-motion",
      "ethers",
      "sweetalert2",
      "react-icons",
      "react-redux",
      "@reduxjs/toolkit",
    ],
    future_improvements: "",
    live_link: "https://nfts.muskatears.com/",
    gitHub_link: "https://github.com/r-tom90/marketplace-v3",
    frontend_download_link:
      "https://github.com/r-tom90/marketplace-v3/archive/refs/heads/main.zip",
    backend_download_link:
      "https://etherscan.io/token/0x213162F3d4FbeC2dB1dEb4666c4d16cF6ab14A7B#code",
    project_image: "/project-emporium.png",
    project_desc:
      "Mint, buy, and sell NFTs on Ethereum blockchain with ThirdWebs SDK power.",
    Type: "NextJS 13",
    indevelopment: false,
  },
  {
    title: "3D Portfolio",
    projectKey: "3dP",
    technology_feature: [
      "JavaScript",
      "React",
      "Tailwind",
      "Framer Motion",
      "ThreeJS",
    ],
    about_this_app:
      "Visually stunning and responsive websites using industry-standard best practices, including reusable code with Higher Order Components, immersive 3D models with ThreeJS and React Three Fiber, seamless animations with Framer Motion, and website performance across all devices.",
    package: [
      "@emailjs/browser",
      "@react-three/drei",
      "@react-three/fiber",
      "framer-motion",
      "maath",
      "react-icons",
      "react-router-dom",
      "react-tilt",
      "three",
    ],
    future_improvements: "",
    live_link: "https://3d-portfolio-tan.vercel.app",
    gitHub_link: "https://github.com/r-tom90/3d-portfolio",
    frontend_download_link:
      "https://github.com/r-tom90/3d-portfolio/archive/refs/heads/main.zip",
    backend_download_link: "",
    project_image: "/project-3dPortfolio.png",
    project_desc:
      "Visually stunning, responsive websites with reusable code, immersive 3D models, smooth animations, and top-notch performance across devices.",
    Type: "React (Vite)",
    indevelopment: false,
  },
  {
    title: "RichEtherscan",
    projectKey: "rEScan",
    technology_feature: ["JavaScript", "React", "Tailwind"],
    about_this_app:
      "Discover RichEtherscan, a feature-rich platform that provides a user-friendly interface and leverages advanced data retrieval from the Ethereum blockchain. With the Alchemy network API, users can effortlessly explore block, transaction, and address history on the Ethereum network. Experience the power of RichEtherscan and delve into the depths of the Ethereum blockchain with ease.",
    package: [
      "@rainbow-me/rainbowkit",
      "@tanstack/react-query",
      "alchemy-sdk",
      "axios",
      "dotenv",
      "embla-carousel-react",
      "ethers",
      "react-icons",
      "react-paginate",
      "react-router-dom",
      "viem",
      "wagmi",
    ],
    future_improvements: "",
    live_link: "https://alchemy-w3-blockexplorer.vercel.app/",
    gitHub_link: "https://github.com/r-tom90/blockexplorer",
    frontend_download_link:
      "https://github.com/r-tom90/blockexplorer/archive/refs/heads/main.zip",
    backend_download_link: "",
    project_image: "/project-richEtherscan.png",
    project_desc:
      "Explore Ethereum blockchain with ease. User-friendly interface, advanced data retrieval, and Alchemy network API integration.",
    Type: "React (Vite)",
    indevelopment: false,
  },
  // {
  //   title: "AdminDashboard Web app",
  //   projectKey: "yF1oJ7wzvWY",
  //   technology_feature: [
  //     "Tailwind",
  //     "React",
  //     "Redux",
  //     "NextJS 13",
  //     "Type Script",
  //     "Node js",
  //     "Express js",
  //     "Firebase",
  //     "Graphql",
  //     "Stripe",
  //   ],

  //   about_this_app:
  //     "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
  //   package: [
  //     "@apollo/client",
  //     "@emotion/react",
  //     "@emotion/styled",
  //     "@mui/material",
  //     "@mui/x-data-grid",
  //     "@nivo/bar",
  //     "@nivo/core",
  //     "@nivo/line",
  //     "@nivo/pie",
  //     "@reduxjs/toolkit",
  //     "@stripe/stripe-js",
  //     "@uiball/loaders",
  //     "encoding",
  //     "firebase",
  //     "graphql",
  //     "jwt-decode",
  //     "react-datepicker",
  //     "next-themes",
  //     "next-auth",
  //     "swiper",
  //     "uuid",
  //     "redux",
  //   ],
  //   future_improvements: "",
  //   live_link: "https://youtu.be/yF1oJ7wzvWY",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
  //   project_image: "/foodd.png",
  //   project_desc:
  //     "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
  //   Type: "NextJS 13",
  //   indevelopment: false,
  // },
  // {
  //   title: "Deliveroo Mobile App",
  //   projectKey: "AxQ_Eli8gtk",
  //   technology_feature: [
  //     "Tailwind",
  //     "React Native",
  //     "Redux",
  //     "Type Script",
  //     "Expo",
  //     "Node js",
  //     "Express js",
  //     "Postger sql",
  //   ],

  //   about_this_app:
  //     "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
  //   package: [
  //     "expo",
  //     "react-native-gesture-handler",
  //     "react-native-heroicons",
  //     "react-native-maps",
  //     "react-native-progress",
  //     "react-native-safe-area-context",
  //     "react-native-screens",
  //     "react-native-svg",
  //     "react-redux",
  //     "typescript",
  //     "nativewind",
  //     "expo-splash-screen",
  //     "@react-navigation/native",
  //     "@react-native-masked-view/masked-view",
  //     "@react-native-async-storage/async-storage",
  //   ],
  //   future_improvements: "",
  //   live_link: "https://youtu.be/AxQ_Eli8gtk",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/Deliveroo_Mobile.apk/archive/refs/heads/main.zip",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
  //   project_image: "",
  //   project_desc:
  //     "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
  //   Type: "React Native",
  //   project_Img_Mobile: [
  //     "/deliveroo1.jpg",
  //     "/roo2.jpg",
  //     "/roo3.jpg",
  //     "/roo4.jpg",
  //     "/roo5.jpg",
  //   ],
  //   indevelopment: false,
  // },
  // {
  //   title: "FullStackFood Order Website",
  //   projectKey: "yF1oJ7wzvWY",
  //   technology_feature: [
  //     "Tailwind",
  //     "React",
  //     "Redux",
  //     "NextJS 13",
  //     "Type Script",
  //     "Node js",
  //     "Express js",
  //     "Firebase",
  //     "Graphql",
  //     "Stripe",
  //   ],

  //   about_this_app:
  //     "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
  //   package: [
  //     "@apollo/client",
  //     "@emotion/react",
  //     "@emotion/styled",
  //     "@mui/material",
  //     "@mui/x-data-grid",
  //     "@nivo/bar",
  //     "@nivo/core",
  //     "@nivo/line",
  //     "@nivo/pie",
  //     "@reduxjs/toolkit",
  //     "@stripe/stripe-js",
  //     "@uiball/loaders",
  //     "encoding",
  //     "firebase",
  //     "graphql",
  //     "jwt-decode",
  //     "react-datepicker",
  //     "next-themes",
  //     "next-auth",
  //     "swiper",
  //     "uuid",
  //     "redux",
  //   ],
  //   future_improvements: "",
  //   live_link: "https://youtu.be/yF1oJ7wzvWY",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/AdminDashboard/archive/refs/heads/main.zip",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
  //   project_image: "/foodorder.png",
  //   project_desc:
  //     "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
  //   Type: "NextJS 13",
  //   indevelopment: false,
  // },

  // {
  //   title: "Fullstack AI ChatGPT ( Clone ) ",
  //   projectKey: "R90bxY4UwPg",
  //   technology_feature: [
  //     "html",
  //     "css",
  //     "Tailwind",
  //     "React",
  //     "Redux",
  //     "NextJS 13",
  //     "Type Script",
  //     "Firebase",
  //   ],

  //   about_this_app:
  //     "This Appp Contain Chate Create , Read , Update , Delete and Google Authentication , Microsoft Authentication , JWT Authentication functionality ",
  //   package: [
  //     "@reduxjs/toolkit",
  //     "@uiball/loaders",
  //     "firebase",
  //     "firebase-admin",
  //     "nextjs-progressbar",
  //     "openai",
  //     "react-firebase-hooks",
  //     "react-icons",
  //     "react-redux",
  //     "react-simple-typewriter",
  //   ],
  //   future_improvements: "",
  //   live_link: "https://youtu.be/R90bxY4UwPg",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/Chat_GPT4/archive/refs/heads/main.zip",
  //   backend_download_link: "",
  //   project_image: "/gpt2.png",
  //   project_desc:
  //     "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth",
  //   Type: "NextJS 13",
  //   indevelopment: false,
  // },
  // {
  //   title: "Nike AdminDashboard Web App ",
  //   projectKey: "v3LJMcWbcDQ",
  //   technology_feature: [
  //     "Tailwind",
  //     "React",
  //     "Redux",
  //     "NextJS 13",
  //     "Type Script",
  //     "Node js",
  //     "Express js",
  //     "Postger sql",
  //     "Firebase",
  //     "Stripe",
  //   ],

  //   about_this_app:
  //     "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
  //   package: [
  //     "@mui/material",
  //     "@nivo/core",
  //     "@nivo/line",
  //     "@nivo/pie",
  //     "@reduxjs/toolkit",
  //     "@splidejs/react-splide",
  //     "@stripe/stripe-js",
  //     "@uiball/loaders",
  //     "next-auth",
  //     "next-themes",
  //     "firebase",
  //     "JavaScript-time-ago",
  //     "jwt-decode",
  //     "react-circular-progressbar",
  //     "react-datepicker",
  //     "react-easy-crop",
  //     "react-icons",
  //     "react-hot-toast",
  //     "react-redux",
  //     "react-tilt",
  //     "uuid",
  //   ],
  //   future_improvements: "",
  //   live_link: "",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/Nike_Shoes/archive/refs/heads/main.zip",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
  //   project_image: "/nikedash.png",
  //   project_desc:
  //     "A Real Time Full Stack Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe",
  //   Type: "NextJS 13",
  //   indevelopment: false,
  // },
  // {
  //   title: "ApexLegnds.com ( Clone )",
  //   projectKey: "IqYbA6ZZ-e4",
  //   technology_feature: [
  //     "html",
  //     "css",
  //     "JavaScript",
  //     "Tailwind",
  //     "React",
  //     "Redux",
  //     "NextJS 13",
  //   ],

  //   about_this_app:
  //     "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive  and Contain Embed video",
  //   package: [
  //     "@reduxjs/toolkit",
  //     "next",
  //     "react-icons",
  //     "react-redux",
  //     "swiper",
  //     "typescript",
  //   ],
  //   future_improvements: "",
  //   live_link: "https://youtu.be/IqYbA6ZZ-e4",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/ApexLegends.com/archive/refs/heads/main.zip",
  //   backend_download_link: "",
  //   project_image: "/apex.png",
  //   project_desc:
  //     "Simple ApexLegnds Game Web application DropDown Feature Complex Responsive",
  //   Type: "NextJS 13",
  //   indevelopment: false,
  // },
  // {
  //   title: "Full Stack SocalMedia ",
  //   projectKey: "cLKsNVSyPMM",
  //   technology_feature: [
  //     "html",
  //     "css",
  //     "JavaScript",
  //     "Tailwind",
  //     "React",
  //     "Redux",
  //     "Node js",
  //     "Express js",
  //   ],
  //   about_this_app:
  //     "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text & RealTime With Pusher ",
  //   package: [
  //     "@mui/icons-material",
  //     "@reduxjs/toolkit",
  //     "formik",
  //     "JavaScript-time-ago",
  //     "jwt-decode",
  //     "material-ui-popup-state",
  //     "pusher-js",
  //     "react-dropzone",
  //     "react-easy-crop",
  //     "react-icons",
  //     "react-redux",
  //     "react-router-dom",
  //     "redux-persist",
  //     "swiper",
  //     "uuid",
  //   ],
  //   future_improvements: "",
  //   live_link: "https://youtu.be/cLKsNVSyPMM",
  //   gitHub_link: "https://github.com/HyatMyat4",
  //   frontend_download_link:
  //     "https://github.com/HyatMyat4/GrapeMedia/archive/refs/heads/main.zip",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/SocialMediaBackend-/archive/refs/heads/main.zip",
  //   project_image: "/reactsocialmedia1.png",
  //   project_desc:
  //     "A Real Time Full Stack SocalMedia application User Can Upload Post With Image , User Can Make Post CRUD Operations & Reaction Feature , Comment CRUD & Contain User Profile CRUD and Friends Add , Remove RealTime Messanger Can send Image,Link,Text",
  //   Type: "React",
  //   indevelopment: false,
  // },
  // {
  //   title: "Profiol Server",
  //   projectKey: "",
  //   technology_feature: ["Golang", "Gin", "Mongo db", "JWT"],
  //   about_this_app: "",
  //   package: [],
  //   future_improvements: "",
  //   live_link: "",
  //   gitHub_link: "",
  //   frontend_download_link: "",
  //   backend_download_link: "",
  //   project_image: "/goserver.png",
  //   project_desc:
  //     "My First Go , Gin Server , Basic CRUD Go Server With Mongodb",
  //   Type: "server",
  //   indevelopment: true,
  // },
  // {
  //   title: "ShoeEcommerce Server",
  //   projectKey: "",
  //   technology_feature: [
  //     "Node js",
  //     "Express js",
  //     "Postger sql",
  //     "Firebase",
  //     "JWT",
  //     "Stripe",
  //   ],
  //   about_this_app: "",
  //   package: [],
  //   future_improvements: "",
  //   live_link: "",
  //   gitHub_link: "",
  //   frontend_download_link: "",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/Nike_Backend/archive/refs/heads/main.zip",
  //   project_image: "/n2.png",
  //   project_desc:
  //     " User authentication Google auth , Facebook auth , Nike Auth ..more , Mind leven CRUD functionality",
  //   Type: "server",
  //   indevelopment: false,
  // },
  // {
  //   title: "FoodOrder & AdminDashboard",
  //   projectKey: "",
  //   technology_feature: [
  //     "Node js",
  //     "Express js",
  //     "Firebase",
  //     "Graphql",
  //     "Stripe",
  //     "JWT",
  //   ],

  //   about_this_app: "",
  //   package: [],
  //   future_improvements: "",
  //   live_link: "",
  //   gitHub_link: "",
  //   frontend_download_link: "",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
  //   project_image: "/n2.png",
  //   project_desc:
  //     "User authentication , Graphql  Mind leven CRUD functionality , Google auth , Facebook auth , Fastfood Auth,",
  //   Type: "server",
  //   indevelopment: false,
  // },
  // {
  //   title: "Deliveroo Server",
  //   projectKey: "",
  //   technology_feature: [
  //     "Node js",
  //     "Express js",
  //     "Firebase",
  //     "Postger sql",
  //     "JWT",
  //   ],

  //   about_this_app: "",
  //   package: [],
  //   future_improvements: "",
  //   live_link: "",
  //   gitHub_link: "",
  //   frontend_download_link: "",
  //   backend_download_link:
  //     "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
  //   project_image: "/n2.png",
  //   project_desc:
  //     "Node js Express With Postger Sql ,FireBase FireStore  CRUD functionality",
  //   Type: "server",
  //   indevelopment: false,
  // },
];

/* //? Portfolio Structure  
  {
    title: "",
    projectKey: "",
    technology_feature: [],
    about_this_app: "",
    package: [],
    future_improvements: "",
    live_link: "",
    gitHub_link: "",
    frontend_download_link: "",
    backend_download_link: "",
    project_image: "",
    project_desc: "",
    Type: "NextJS 13",
    indevelopment: false,
  },
*/

export const colour: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
];
